[
    {
    id: 4,
    source: {
      stationCode: "S",
      stationNameHindi: "नवाडे रोड",
      stationNameEnglish: "NAVADE ROAD",
      stationNameMarathi: "नावडे रोड",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "पनवेल",
      stationNameEnglish: "PANVEL",
      stationNameMarathi: "पनवेल",
    },
    price: 5,
    via: "KLMC",
    distance: "8 km",
    travelTime: 25,
  },
  {
    id: 1,
    source: {
      stationCode: "S",
      stationNameHindi: "दिवा",
      stationNameEnglish: "DIVA",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    price: 15,
    via: "CLA",
    distance: "43 km",
    travelTime: 60,
  },
  {
    id: 2,
    source: {
      stationCode: "S",
      stationNameHindi: "खारघर",
      stationNameEnglish: "KHARGHAR",
      stationNameMarathi: "खारघर",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "राबाडा",
      stationNameEnglish: "RABADA",
      stationNameMarathi: "राबाडा",
    },
    price: 10,
    via: "JNJ-TUH",
    distance: "18 km",
    travelTime: 40,
  },
  
  {
    id: 3,
    source: {
      stationCode: "S",
      stationNameHindi: "दिवा",
      stationNameEnglish: "DIVA",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "ठाणे",
      stationNameEnglish: "THANE",
      stationNameMarathi: "ठाणे",
    },
    price: 5,
    via: "------",
    distance: "10 km",
    travelTime: 25,
  },
  {
    id: 5,
    source: {
      stationCode: "S",
      stationNameHindi: "पनवेल",
      stationNameEnglish: "PANVEL",
      stationNameMarathi: "पनवेल",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "ठाणे",
      stationNameEnglish: "THANE",
      stationNameMarathi: "ठाणे",
    },
    price: 15,
    via: "JNJ-TUH",
    distance: "27 km",
    travelTime: 40,
  },
  {
    id: 6,
    source: {
      stationCode: "S",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "पनवेल",
      stationNameEnglish: "PANVEL",
      stationNameMarathi: "पनवेल",
    },
    price: 20,
    via: "CLA",
    distance: "49 km",
    travelTime: 50,
  },
  {
    id: 7,
    source: {
      stationCode: "S",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "पनवेल",
      stationNameEnglish: "PANVEL",
      stationNameMarathi: "पनवेल",
    },
    price: 25,
    via: "TNA-TUH-JNJ",
    distance: "68 km",
    travelTime: 50,
  },
{
  id:8,
  source: {
    stationCode: "S",
    stationNameHindi: "दिवा",
    stationNameEnglish: "DIVA",
    stationNameMarathi: "दिवा",
  },
  destination: {
    stationCode: "D",
    stationNameHindi: "पनवेल",
    stationNameEnglish: "PANVEL",
    stationNameMarathi: "पनवेल",
  },
  price: 10,
  via: "TPND",
  distance: "17 km",
  travelTime: 40,
},
{
  id: 9,
  source: {
    stationCode: "S",
    stationNameHindi: "नवाडे रोड",
    stationNameEnglish: "NAVADE ROAD",
    stationNameMarathi: "नावडे रोड",
  },
  destination: {
    stationCode: "D",
    stationNameHindi: "छ. शिवाजी महा. ट.",
    stationNameEnglish: "C SHIVAJI MAH T",
    stationNameMarathi: "छ. शिवाजी महा ट",
  },
  price: 20,
  via: "PNVL-SNCR-CLA-VDLR",
  distance: "43 km",
  travelTime: 90,
},  {
    id: 10,
    source: {
      stationCode: "S",
      stationNameHindi: "पनवेल",
      stationNameEnglish: "PANVEL",
      stationNameMarathi: "पनवेल",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "कोपर",
      stationNameEnglish: "KOPER",
      stationNameMarathi: "कॉपर",
    },
    price: 15,
    via: "------",
    distance: "31 km",
    travelTime: 25,
  },
{
    id: 11,
    source: {
      stationCode: "S",
      stationNameHindi: "दिवा",
      stationNameEnglish: "DIVA",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "टिटवाला",
      stationNameEnglish: "TITWALA",
      stationNameMarathi: "टिटवाळा",
    },
    price: 10,
    via: "CLA",
    distance: "22 km",
    travelTime: 60,
  },
{
    id: 12,
    source: {
      stationCode: "S",
      stationNameHindi: "अंधेरी",
      stationNameEnglish: "ANDHERI",
      stationNameMarathi: "अंधेरी",
    },
    destination: {
      stationCode: "D",
      stationNameHindi: "वसई रोड",
      stationNameEnglish: "VASAI ROAD",
      stationNameMarathi: "वसई रोड",
    },
    price: 10,
    via: "---",
    distance: "30 km",
    travelTime: 60,
  },

];
