[
  {
    id: 4,
    source: {
      stationNameEnglish: "NILAJE",
      stationNameHindi: "नवाडे रोड",
      stationNameMarathi: "नावडे रोड",
    },
    destination: {
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    price: {
      monthly: { SECOND: 385, FIRST: 770 },
      journey: { SECOND: 25, FIRST: 115 },
      returnT: { SECOND: 45, FIRST: 210 },
    },
    via: "1RT>>PNVL-CLA-VDLR-SNRD",
    distance: "70 km",
    travelTime: 90,
  },
  {
    id: 1,
    source: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "दिवा",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    price: {
      monthly: { SECOND: 315, FIRST: 630 },
      journey: { SECOND: 20, FIRST: 100 },
      returnT: { SECOND: 35, FIRST: 185 },
    },
    via: "1RT>>DIVA-TNA-CLA-DR",
    distance: "69 km",
    travelTime: 60,
  },
  {
    id: 20,
    source: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "नवाडे रोड",
      stationNameMarathi: "नावडे रोड",
    },
    destination: {
      stationNameEnglish: "Thane",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    price: {
      monthly: { SECOND: 295, FIRST: 590 },
      journey: { SECOND: 15, FIRST: 90 },
      returnT: { SECOND: 30, FIRST: 165 },
    },
    via: "1RT>>JNJ-TUH",
    distance: "35 km",
    travelTime: 90,
  },
  {
    id: 2,
    source: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "खारघर",
      stationNameMarathi: "खारघर",
    },
    destination: {
      stationNameEnglish: "KOPAR",
      stationNameHindi: "राबाडा",
      stationNameMarathi: "राबाडा",
    },
    price: {
      monthly: { SECOND: 215, FIRST: 755 },
      journey: { SECOND: 15, FIRST: 85 },
      returnT: { SECOND: 30, FIRST: 170 },
    },
    via: "JNJ-TUH",
    distance: "18 km",
    travelTime: 40,
  },
  {
    id: 3,
    source: {
      stationNameEnglish: "DIVA",
      stationNameHindi: "दिवा",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationNameEnglish: "THANE",
      stationNameHindi: "ठाणे",
      stationNameMarathi: "ठाणे",
    },
    price: {
      monthly: { SECOND: 100, FIRST: 300 },
      journey: { SECOND: 5, FIRST: 25 },
      returnT: { SECOND: 10, FIRST: 50 },
    },
    via: "------",
    distance: "10 km",
    travelTime: 25,
  },
  {
    id: 5,
    source: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    destination: {
      stationNameEnglish: "THANE",
      stationNameHindi: "ठाणे",
      stationNameMarathi: "ठाणे",
    },
    price: {
      monthly: { SECOND: 215, FIRST: 645 },
      journey: { SECOND: 15, FIRST: 90 },
      returnT: { SECOND: 30, FIRST: 165 },
    },
    via: "JNJ-TUH",
    distance: "27 km",
    travelTime: 40,
  },
  {
    id: 6,
    source: {
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    destination: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    price: {
      monthly: { SECOND: 270, FIRST: 810 },
      journey: { SECOND: 20, FIRST: 100 },
      returnT: { SECOND: 35, FIRST: 185 },
    },
    via: "CLA",
    distance: "49 km",
    travelTime: 50,
  },
  {
    id: 7,
    source: {
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    destination: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    price: {
      monthly: { SECOND: 315, FIRST: 945 },
      journey: { SECOND: 25, FIRST: 115 },
      returnT: { SECOND: 45, FIRST: 210 },
    },
    via: "TNA-TUH-JNJ",
    distance: "68 km",
    travelTime: 50,
  },
  {
    id: 8,
    source: {
      stationNameEnglish: "DIVA",
      stationNameHindi: "दिवा",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    price: {
      monthly: { SECOND: 150, FIRST: 510 },
      journey: { SECOND: 10, FIRST: 85 },
      returnT: { SECOND: 20, FIRST: 150 },
    },
    via: "TPND",
    distance: "17 km",
    travelTime: 40,
  },
  {
    id: 9,
    source: {
      stationNameEnglish: "NAVADE ROAD",
      stationNameHindi: "नवाडे रोड",
      stationNameMarathi: "नावडे रोड",
    },
    destination: {
      stationNameEnglish: "C SHIVAJI MAH T",
      stationNameHindi: "छ. शिवाजी महा. ट.",
      stationNameMarathi: "छ. शिवाजी महा ट",
    },
    price: {
      monthly: { SECOND: 270, FIRST: 540 },
      journey: { SECOND: 20, FIRST: 20 },
      returnT: { SECOND: 35, FIRST: 35 },
    },
    via: "PNVL-SNCR-CLA-VDLR",
    distance: "43 km",
    travelTime: 90,
  },
  {
    id: 10,
    source: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    destination: {
      stationNameEnglish: "KOPER",
      stationNameHindi: "कोपर",
      stationNameMarathi: "कॉपर",
    },
    price: {
      monthly: { SECOND: 215, FIRST: 215 },
      journey: { SECOND: 15, FIRST: 100 },
      returnT: { SECOND: 30, FIRST: 185 },
    },
    via: "------",
    distance: "31 km",
    travelTime: 25,
  },
  {
    id: 11,
    source: {
      stationNameEnglish: "DIVA",
      stationNameHindi: "दिवा",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationNameEnglish: "KHOPOLI",
      stationNameHindi: "खोपोली",
      stationNameMarathi: "खोपोली",
    },
    price: {
      monthly: { SECOND: 315, FIRST: 945 },
      journey: { SECOND: 20, FIRST: 115 },
      returnT: { SECOND: 35, FIRST: 210 },
    },
    via: "KYN",
    distance: "72 km",
    travelTime: 45,
  },
  {
    id: 14,
    source: {
      stationNameEnglish: "DIVA",
      stationNameHindi: "दिवा",
      stationNameMarathi: "दिवा",
    },
    destination: {
      stationNameEnglish: "KHOPOLI",
      stationNameHindi: "खोपोली",
      stationNameMarathi: "खोपोली",
    },
    price: {
      monthly: { SECOND: 150, FIRST: 420 },
      journey: { SECOND: 10, FIRST: 60 },
      returnT: { SECOND: 20, FIRST: 110 },
    },
    via: "KYN",
    distance: "22 km",
    travelTime: 30,
  },
  {
    id: 12,
    source: {
      stationNameEnglish: "ANDHERI",
      stationNameHindi: "अंधेरी",
      stationNameMarathi: "अंधेरी",
    },
    destination: {
      stationNameEnglish: "VASAI ROAD",
      stationNameHindi: "वसई रोड",
      stationNameMarathi: "वसई रोड",
    },
    price: {
      monthly: { SECOND: 150, FIRST: 510 },
      journey: { SECOND: 10, FIRST: 85 },
      returnT: { SECOND: 20, FIRST: 150 },
    },
    via: "-----",
    distance: "30 km",
    travelTime: 60,
  },
  {
    id: 13,
    source: {
      stationNameEnglish: "VASAI ROAD",
      stationNameHindi: "वसई रोड",
      stationNameMarathi: "वसई रोड",
    },
    destination: {
      stationNameEnglish: "PANVEL",
      stationNameHindi: "पनवेल",
      stationNameMarathi: "पनवेल",
    },
    price: {
      monthly: { SECOND: 270, FIRST: 840 },
      journey: { SECOND: 20, FIRST: 105 },
      returnT: { SECOND: 35, FIRST: 195 },
    },
    via: "BSR",
    distance: "68 km",
    travelTime: 25,
  },
];
